Ryzen 7000
pop-os/linux-firmware pull request #24
Opened 2022-09-27 16:02 UTC by jackpot51

This pulls in a number of upstream updates to linux-firmware, and will likely include the necessary updates to support Ryzen 7000 Integrated graphics. I also anticipate updates to Mesa.

2022-09-27 16:50 UTC, 13r0ck submitted a review, later dismissed

2022-09-27 17:43 UTC, leviport requested changes
I'm getting a dependency problem when trying to install this:
```
system76@pop-os:~$ sudo apt install linux-firmware
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pop-desktop : Depends: linux-system76 but it is not going to be installed
               Recommends: io.elementary.sideload but it is not installable
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

2022-09-27 18:48 UTC, jackpot51 commented
I see it too. I might have to roll this back a bit, it has dependencies on amd64-microcode updates we don't have in 22.04

2022-09-27 18:50 UTC, jackpot51 commented
Rolled back to latest Ubuntu 22.04 version. Good to try, may not have the updates we need.

2022-09-29 17:23 UTC, leviport commented
This and https://github.com/pop-os/mesa/pull/8 are not fixing the 7000 series iGPU. It looks more like a boot failure though, so maybe I should try a newer kernel or something.

2022-10-11 14:49 UTC, jackpot51 commented
I pushed the 22.10 linux-firmware again, this time without the dependency requirement on amd64-microcode.

2022-10-11 19:26 UTC, 13r0ck approved these changes

2022-10-14 18:25 UTC, leviport approved these changes

2022-10-14 19:54 UTC, merged