linux-firmware sync with ubuntu/mantic
pop-os/linux-firmware pull request #40
Opened 2023-11-21 15:59 UTC by mmstick

Last commit to Ubuntu's mantic branch was [November 16th](https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-firmware/commit/?h=mantic&id=ab8c121ffde2a131da96f30e66768b59cf36d410). There are some AMD DRM changes in here that may fix issues seen with Steam on a particular AMD card.

2023-11-21 20:34 UTC, leviport requested changes
Unfortunately this doesn't have any effect on the RX 7600 + Steam launching bug. 

Side note: even though Gnome + Wayland is also affected by this bug, COSMIC DE launches Steam without issue.

2023-11-21 20:47 UTC, mmstick commented
Then the issue may be somewhere in GNOME/Mesa.

2023-11-26 16:28 UTC, randomf commented
This PR fixes no sleep and no bluetooth issue on Thinkpad T14s G3 AMD on kernel 6.5.6.

2023-11-27 15:36 UTC, leviport commented
Despite it not fixing the Steam bug on the RX 7600, I think this update is still desirable. We will continue testing it.

2023-11-27 17:33 UTC, jackpot51 approved these changes

2023-11-28 19:33 UTC, leviport approved these changes
I've tested this on a handful of various models and I'm not seeing any regressions.

2023-11-28 19:36 UTC, merged